# Generated by Django 4.2.27 on 2025-12-15 07:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groq_api_key_encrypted', models.TextField(blank=True, default='', help_text='Encrypted Groq API key')),
                ('is_active', models.BooleanField(default=False, help_text='Whether the API configuration is active')),
                ('default_model', models.CharField(default='llama-3.1-8b-instant', help_text='Default LLM model to use', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configuration',
            },
        ),
        migrations.CreateModel(
            name='LLMTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the LLM call was made')),
                ('model_name', models.CharField(db_index=True, help_text='Name of the LLM model used (e.g., llama-3.1-70b)', max_length=100)),
                ('prompt', models.TextField(help_text='The input prompt sent to the LLM')),
                ('response', models.TextField(blank=True, default='', help_text='The response received from the LLM')),
                ('input_tokens', models.IntegerField(default=0, help_text='Number of input tokens', validators=[django.core.validators.MinValueValidator(0)])),
                ('output_tokens', models.IntegerField(default=0, help_text='Number of output tokens', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens (input + output)', validators=[django.core.validators.MinValueValidator(0)])),
                ('latency_ms', models.FloatField(default=0.0, help_text='Response time in milliseconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0.0, help_text='Calculated cost in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, default='success', help_text='Status of the LLM call', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error message if the call failed', null=True)),
                ('user_identifier', models.CharField(blank=True, db_index=True, default='anonymous', help_text='Identifier for the user who made the call', max_length=255)),
                ('feature_name', models.CharField(blank=True, db_index=True, default='general', help_text='Feature or component that triggered the LLM call', max_length=100)),
                ('request_id', models.CharField(blank=True, help_text='Unique request ID from Groq API', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'LLM Trace',
                'verbose_name_plural': 'LLM Traces',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional comment from the user', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the feedback was submitted')),
                ('trace', models.ForeignKey(help_text='The LLM trace this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='dashboard.llmtrace')),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='llmtrace',
            index=models.Index(fields=['-timestamp'], name='dashboard_l_timesta_6c6704_idx'),
        ),
        migrations.AddIndex(
            model_name='llmtrace',
            index=models.Index(fields=['status'], name='dashboard_l_status_e6f232_idx'),
        ),
        migrations.AddIndex(
            model_name='llmtrace',
            index=models.Index(fields=['model_name'], name='dashboard_l_model_n_adb812_idx'),
        ),
        migrations.AddIndex(
            model_name='llmtrace',
            index=models.Index(fields=['user_identifier'], name='dashboard_l_user_id_a0ea54_idx'),
        ),
        migrations.AddIndex(
            model_name='llmtrace',
            index=models.Index(fields=['feature_name'], name='dashboard_l_feature_5ecf1f_idx'),
        ),
        migrations.AddIndex(
            model_name='llmtrace',
            index=models.Index(fields=['timestamp', 'status'], name='dashboard_l_timesta_1d070c_idx'),
        ),
    ]
