# Generated by Django 4.2.27 on 2025-12-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFeedback',
        ),
    ]
