# Generated by Django 4.2.27 on 2025-12-15 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_userfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '👎 Poor'), (2, '😐 Fair'), (3, '👍 Good'), (4, '⭐ Great'), (5, '🌟 Excellent')], help_text='User rating of the response (1-5)')),
                ('comment', models.TextField(blank=True, default='', help_text='Optional user comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the feedback was submitted')),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='llmtrace',
            name='dashboard_l_user_id_a0ea54_idx',
        ),
        migrations.RemoveIndex(
            model_name='llmtrace',
            name='dashboard_l_feature_5ecf1f_idx',
        ),
        migrations.RemoveField(
            model_name='llmtrace',
            name='feature_name',
        ),
        migrations.RemoveField(
            model_name='llmtrace',
            name='user_identifier',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='trace',
            field=models.ForeignKey(help_text='The LLM trace this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='dashboard.llmtrace'),
        ),
    ]
