# Generated by Django 4.2.27 on 2025-12-16 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_userfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmtrace',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who made this LLM call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_traces', to=settings.AUTH_USER_MODEL),
        ),
    ]
